### ISSUE TITLE
Structure question about BEM

### ISSUE THREAD

**Issue by simonfranzen** [alanbsmith/component-library-starter#3]
We used BEM a lot and thinking about setting up a component library for react which follows BEM guidelines. No I am confused about your structure. You separate blocks, elements and modifiers in different folders. When the library grows this will become a mess or am I wrong? I thought that each component holds it's own elements and modifiers, because an element and modifiers, in BEM, only belong to one block. And when you do this you can just reuse the one component of that library. 

Maybe I am wrong :) Please give me hint

---- after looking into the project
I see in the code that the Button for example uses global modifiers and then you can implement a custom. That's fine, I got it. So global modifiers and custom for a block. But why storing elements in a separate folder ? An Element only belongs to one block, so it should be moved there. If you want to have a global "Icon", p or Text -> than this is actually a block.

**Comment by indiesquidge** [comment]
@simonfranzen, strictly speaking from a traditional BEM methodology, I think you're right—elements belong to a single block. However, the pattern that Alan outlines here allows for elements to also be used on their own.

I highly recommend reading the [blog post](https://tech.decisiv.com/structuring-our-styled-components-part-i-2bf21fa64b28) that Alan wrote that relates to this starter lib.
