### ISSUE TITLE
Validating modifiers in a parent component throws warnings for customModifiers defined in child components

### ISSUE THREAD

**Issue by robbie-hinman** [alanbsmith/component-library-starter#4]
## EXPECTED BEHAVIOR
When defining a custom modifier in a child component, I would not expect to see proptype warnings from it's parent component saying those modifiers are invalid.   

## ACTUAL BEHAVIOR
These warnings come from parent components that use `styleModifierPropTypes`, that don't seem to allow for the modifiers of the children.

## STEPS TO REPRODUCE
1. Clone in a fresh component-library-starter project.
2. Inside elements/Icon/index.js add modifier validation by importing `styleModifierPropTypes` and adding: 
```
Icon.propTypes = {
  modifiers: styleModifierPropTypes(modifierConfig),
}
```
3. Observe in console the following:
> Warning: Failed prop type: Invalid modifier left used in prop modifiers[0] and supplied to Styled(UnstyledIcon). Validation failed.
>     in Styled(UnstyledIcon) (created by PreviewComponent)
>     in PreviewComponent
>     in ThemeProvider (created by ThemeWrapper)

This is because Button.Icon defines a customModifier 'left'.  

Is there a recommended way to validate modifiers for components that are built off of other components?

Thanks!

**Comment by robbie-hinman** [comment]
Moving to here: https://github.com/Decisiv/styled-components-modifiers/issues/13

**Comment by alanbsmith** [comment]
Sorry, I missed this @robbie-hinman. Yes, SCM is the place for that question. We'll try to get an answer for you shortly.
